// Mock data for PixelShrink Studio (frontend-only)
import { Scissors, Eraser, Crop as CropIcon, FileText, FileType2, Video, Music, Sparkles, Smile, Type, Image as ImageIcon, Repeat, Stamp, ShieldOff, FileStack, Laugh, LayoutGrid, Combine, StickyNote, Braces, KeyRound, GitCompare, QrCode, Binary, FileCode2, AlignLeft, Images } from 'lucide-react';

export const TOOLS = [
  {
    key: 'shrink',
    label: 'Shrink Image',
    short: 'Shrink',
    icon: Scissors,
    headline: 'Image Shrinker — resize images online, free.',
    sub: 'Shrink JPG, PNG, WEBP and more without losing crispness. Perfect for socials, email and the web.',
    seoTitle: 'Free Image Resizer Online | Shrink Images Without Quality Loss',
    seoDesc: 'Resize and compress JPG, PNG, WEBP images online. Shrink for web, email and social media while maintaining quality.',
    seoKeywords: 'image resizer, shrink image, compress image, resize image online, image compressor',
  },
  {
    key: 'removebg',
    label: 'Remove Background',
    short: 'No-BG',
    icon: Eraser,
    headline: 'Remove Background — instant, AI-powered, free.',
    sub: 'Erase backgrounds in one click. Get crisp transparent PNGs ready for product shots, designs and social posts.',
    seoTitle: 'Remove Background from Image | Free AI-Powered Background Remover',
    seoDesc: 'Remove image backgrounds instantly with AI. Get transparent PNGs for product photos, designs and social media.',
    seoKeywords: 'remove background, background remover, transparent PNG, AI background removal',
  },
  {
    key: 'crop',
    label: 'Crop Image',
    short: 'Crop',
    icon: CropIcon,
    headline: 'Crop Image — pick the perfect frame, free.',
    sub: 'Drag to crop, lock to a preset aspect ratio, and download the result. All in your browser.',
    seoTitle: 'Free Online Image Cropper | Crop Photos to Perfect Size',
    seoDesc: 'Crop images online with preset aspect ratios. Perfect for thumbnails, profile pictures and social media.',
    seoKeywords: 'image cropper, crop photo, resize aspect ratio, thumbnail maker, crop image online',
  },
  {
    key: 'filters',
    label: 'Image Filters',
    short: 'Filters',
    icon: Sparkles,
    headline: 'Image Filters — adjust brightness, contrast & more, free.',
    sub: 'Apply professional photo filters instantly. Adjust brightness, contrast, and grayscale right in your browser.',
    seoTitle: 'Free Online Photo Filters & Editor | Adjust Brightness, Contrast & Grayscale',
    seoDesc: 'Apply professional photo filters instantly. Adjust brightness, contrast, and grayscale on your images.',
    seoKeywords: 'photo filters, image editor, brightness contrast adjustment, photo effects, online photo editor',
  },
  {
    key: 'moustachify',
    label: 'Moustachify',
    short: 'Stache',
    icon: Smile,
    headline: 'Moustachify — add a moustache to any face, free.',
    sub: 'Automatic face detection adds a perfect moustache to your photo. Choose from 6 fun styles.',
    seoTitle: 'Moustachify — Add Moustache to Photos | Free Face Detection Tool',
    seoDesc: 'Add fun moustaches to any face with AI face detection. Choose from 6 styles: handlebar, pencil, walrus, curly, chevron, dutch.',
    seoKeywords: 'moustachify, add moustache, face detection, fun photo editor, mustache filter, photo effects',
  },
  {
    key: 'pdf2word',
    label: 'PDF → Word',
    short: 'PDF→Word',
    icon: FileText,
    headline: 'PDF to Word — extract text from PDFs, free.',
    sub: 'Convert text-based PDFs into editable Word documents. Layout-light PDFs convert best.',
    seoTitle: 'Convert PDF to Word Online | Free PDF to Docx Converter',
    seoDesc: 'Convert text-based PDF files to editable Word documents. Extract text and maintain formatting.',
    seoKeywords: 'pdf to word, convert pdf to docx, pdf converter, extract text from pdf',
  },
  {
    key: 'word2pdf',
    label: 'Word → PDF',
    short: 'Word→PDF',
    icon: FileType2,
    headline: 'Word to PDF — turn docs into PDFs, free.',
    sub: 'Drop your .docx file and get back a clean, shareable PDF in seconds.',
    seoTitle: 'Convert Word to PDF Online | Free DOCX to PDF Converter',
    seoDesc: 'Convert Word documents (.docx) to PDF instantly. Create professional PDFs for sharing and printing.',
    seoKeywords: 'word to pdf, convert docx to pdf, pdf converter, docx to pdf converter',
  },
  {
    key: 'compressvideo',
    label: 'Compress Video',
    short: 'Video',
    icon: Video,
    headline: 'Video Compressor — shrink video files, free.',
    sub: 'Compress MP4, MOV and WebM files without losing too much quality. Runs entirely in your browser.',
    seoTitle: 'Compress Video Online | Free MP4, MOV & WebM Compressor',
    seoDesc: 'Reduce video file size without losing quality. Compress MP4, MOV, WebM for email and social media.',
    seoKeywords: 'video compressor, compress video, reduce video size, mp4 compressor, video compression',
  },
  {
    key: 'video2mp3',
    label: 'Video → MP3',
    short: 'V→MP3',
    icon: Music,
    headline: 'Video to MP3 — extract audio, free.',
    sub: 'Pull the audio out of any video file you own. Get a clean MP3 ready to share.',
    seoTitle: 'Convert Video to MP3 | Free Audio Extraction Tool',
    seoDesc: 'Extract audio from videos and download as MP3. Works with MP4, MOV, WebM files.',
    seoKeywords: 'video to mp3, extract audio, convert video to audio, mp3 converter, audio extractor',
  },
  {
    key: 'aimagegen',
    label: 'AI Image Generator',
    short: 'AI Gen',
    icon: ImageIcon,
    headline: 'AI Image Generator — create art from text prompts, free.',
    sub: 'Generate AI images from prompts using free Hugging Face models. Choose style, size and settings, then download instantly.',
    seoTitle: 'Free AI Image Generator | Create Images from Text Prompts',
    seoDesc: 'Generate stunning AI images from text prompts for free. No sign-up required. Create art, designs, and graphics instantly.',
    seoKeywords: 'AI image generator, text to image, AI art, image generation, free AI generator, create images',
  },
  {
    key: 'texttoimage',
    label: 'Text to Image',
    short: 'Txt→Img',
    icon: Type,
    headline: 'Text to Image — create stunning graphics from text, free.',
    sub: 'Turn any text into a beautiful image. Choose fonts, colors, effects and canvas sizes for social media.',
    seoTitle: 'Text to Image Creator | Free Online Generator',
    seoDesc: 'Create beautiful images from text. Customize fonts, colors, effects and download instantly.',
    seoKeywords: 'text to image, image generator, create images, text graphics, quote maker',
  },
  {
    key: 'convert',
    label: 'Convert Image',
    short: 'Convert',
    icon: Repeat,
    headline: 'Image Converter — switch formats in a click, free.',
    sub: 'Convert between PNG, JPG, WEBP and AVIF with adjustable quality. All in your browser.',
    seoTitle: 'Free Image Format Converter | PNG, JPG, WEBP & AVIF',
    seoDesc: 'Convert images between PNG, JPG, WEBP and AVIF online for free. Adjust quality and download instantly.',
    seoKeywords: 'image converter, png to jpg, jpg to png, webp converter, avif converter',
  },
  {
    key: 'watermark',
    label: 'Watermark',
    short: 'Watermark',
    icon: Stamp,
    headline: 'Watermark Maker — protect your photos, free.',
    sub: 'Add a text or logo watermark with full control over position, size and opacity.',
    seoTitle: 'Free Watermark Maker | Add Text or Logo Watermark to Photos',
    seoDesc: 'Add a text or logo watermark to your images online for free. Control position, opacity and size.',
    seoKeywords: 'add watermark, watermark image, logo watermark, text watermark',
  },
  {
    key: 'exif',
    label: 'EXIF Remover',
    short: 'EXIF',
    icon: ShieldOff,
    headline: 'EXIF Viewer & Remover — protect your privacy, free.',
    sub: 'See hidden camera info and GPS location baked into your photos, then strip it all in one click.',
    seoTitle: 'Free EXIF Viewer & Metadata Remover | Strip GPS & Camera Data',
    seoDesc: 'View hidden EXIF metadata in your photos and strip it all with one click before sharing.',
    seoKeywords: 'exif viewer, remove metadata, strip exif, remove gps from photo, metadata remover',
  },
  {
    key: 'batchrename',
    label: 'Bulk File Renaming',
    short: 'Bulk Rename',
    icon: FileStack,
    headline: 'Bulk File Renaming — rename dozens of files at once, free.',
    sub: 'Got a folder of messy filenames? Set one naming pattern and rename every file at once — no more renaming them one by one.',
    seoTitle: 'Free Bulk File Renaming Tool | Rename Multiple Files at Once',
    seoDesc: 'Rename dozens of files at once with one naming pattern and automatic numbering — no more renaming files one by one. Download them all as a ZIP.',
    seoKeywords: 'bulk file renaming, bulk rename files, batch rename, rename multiple files, sequential file rename, rename files online',
  },
  {
    key: 'meme',
    label: 'Meme Generator',
    short: 'Meme',
    icon: Laugh,
    headline: 'Meme Generator — classic captions, free.',
    sub: 'Add bold top and bottom text to any photo and download your meme instantly.',
    seoTitle: 'Free Meme Generator | Add Top & Bottom Captions to Photos',
    seoDesc: 'Create classic memes online for free. Add bold top and bottom captions to any image.',
    seoKeywords: 'meme generator, meme maker, create meme, caption generator',
  },
  {
    key: 'collage',
    label: 'Photo Collage',
    short: 'Collage',
    icon: LayoutGrid,
    headline: 'Photo Collage Maker — merge photos into one grid, free.',
    sub: 'Combine 2 to 9 images into a single grid collage with adjustable columns and spacing.',
    seoTitle: 'Free Photo Collage Maker | Merge Multiple Images into One',
    seoDesc: 'Combine 2 to 9 photos into a single grid collage online for free.',
    seoKeywords: 'photo collage maker, image collage, merge photos, combine images',
  },
  {
    key: 'pdforganizer',
    label: 'PDF Organizer',
    short: 'PDF Tools',
    icon: Combine,
    headline: 'PDF Organizer — merge, split and reorder pages, free.',
    sub: 'Combine multiple PDFs into one, or delete, reorder and split pages from a single PDF.',
    seoTitle: 'Free PDF Merge, Split & Reorder Tool | Organize PDF Pages',
    seoDesc: 'Merge multiple PDFs into one, or split, delete and reorder pages in a single PDF.',
    seoKeywords: 'merge pdf, split pdf, reorder pdf pages, delete pdf pages, combine pdf files',
  },
  {
    key: 'notepad',
    label: 'PSnotepad',
    short: 'PSnotepad',
    icon: StickyNote,
    headline: 'PSnotepad — a quick scratchpad that autosaves, free.',
    sub: 'Jot down notes or drafts right in your browser. Autosaves as you type, no account needed.',
    seoTitle: 'PSnotepad — Free Online Notepad | Autosaving Browser Scratchpad',
    seoDesc: 'PSnotepad is a free online notepad that autosaves as you type. No sign-up, no uploads — your notes stay in your browser.',
    seoKeywords: 'online notepad, free notepad, autosave notes, browser scratchpad, notepad online, PSnotepad',
  },
  {
    key: 'jsonformatter',
    label: 'JSON Formatter',
    short: 'JSON',
    icon: Braces,
    headline: 'JSON Formatter — validate and beautify JSON, free.',
    sub: 'Paste messy or minified JSON and get it validated, indented and easy to read — or minified down.',
    seoTitle: 'Free JSON Formatter & Validator Online',
    seoDesc: 'Format, validate and minify JSON online for free. Instantly spot errors and get beautifully indented output.',
    seoKeywords: 'json formatter, json validator, format json online, minify json, json beautifier',
  },
  {
    key: 'passwordgen',
    label: 'Password Generator',
    short: 'Password',
    icon: KeyRound,
    headline: 'Password Generator — strong, random passwords, free.',
    sub: 'Generate a secure random password with your choice of length and character types, right in your browser.',
    seoTitle: 'Free Secure Password Generator Online',
    seoDesc: 'Generate strong, random passwords online for free. Customize length and character types. Nothing sent over the network.',
    seoKeywords: 'password generator, random password, secure password generator, strong password online',
  },
  {
    key: 'diffchecker',
    label: 'Diff Checker',
    short: 'Diff',
    icon: GitCompare,
    headline: 'Diff Checker — compare two texts, free.',
    sub: 'Paste two versions of a text and see exactly what changed, word by word.',
    seoTitle: 'Free Online Text Diff Checker | Compare Two Texts',
    seoDesc: 'Compare two blocks of text online for free and instantly see additions and deletions highlighted.',
    seoKeywords: 'diff checker, text compare, compare text online, text difference tool',
  },
  {
    key: 'qrcode',
    label: 'QR Code Generator',
    short: 'QR Code',
    icon: QrCode,
    headline: 'QR Code Generator — text or URL to QR code, free.',
    sub: 'Turn any text, URL or message into a scannable QR code and download it as a PNG.',
    seoTitle: 'Free QR Code Generator Online | Text & URL to QR',
    seoDesc: 'Generate QR codes online for free from any text or URL. Download instantly as a PNG. No uploads required.',
    seoKeywords: 'qr code generator, free qr code, create qr code, url to qr code, text to qr code',
  },
  {
    key: 'base64',
    label: 'Base64 Encoder/Decoder',
    short: 'Base64',
    icon: Binary,
    headline: 'Base64 Encoder/Decoder — convert text instantly, free.',
    sub: 'Encode text to Base64 or decode Base64 back to text, with full Unicode support.',
    seoTitle: 'Free Base64 Encoder & Decoder Online',
    seoDesc: 'Encode or decode Base64 online for free, with full Unicode support for emoji and non-Latin text.',
    seoKeywords: 'base64 encoder, base64 decoder, encode base64, decode base64, base64 converter',
  },
  {
    key: 'mdpreview',
    label: 'Markdown Previewer',
    short: 'Markdown',
    icon: FileCode2,
    headline: 'Markdown Previewer — live preview as you type, free.',
    sub: 'Write Markdown and see it rendered live, side by side. Great for README files and GitHub comments.',
    seoTitle: 'Free Online Markdown Previewer & Editor',
    seoDesc: 'Write and preview Markdown live online for free. Perfect for README files, comments and documentation.',
    seoKeywords: 'markdown previewer, markdown editor online, live markdown preview, md to html',
  },
  {
    key: 'wordcounter',
    label: 'Word Counter',
    short: 'Word Count',
    icon: AlignLeft,
    headline: 'Word Counter — words, characters & reading time, free.',
    sub: 'Get live counts of words, characters, sentences and paragraphs, plus an estimated reading time.',
    seoTitle: 'Free Word Counter & Character Counter Online',
    seoDesc: 'Count words, characters, sentences and paragraphs online for free, with estimated reading time. Updates live.',
    seoKeywords: 'word counter, character counter, count words online, reading time calculator',
  },
  {
    key: 'img2pdf',
    label: 'Image to PDF',
    short: 'Img→PDF',
    icon: Images,
    headline: 'Image to PDF — turn photos into a PDF, free.',
    sub: 'Convert one or many images into a PDF. Combine them into a single file, or keep each as its own PDF.',
    seoTitle: 'Free Image to PDF Converter Online | JPG, PNG to PDF',
    seoDesc: 'Convert JPG, PNG and WEBP images to PDF online for free. Combine multiple images into one PDF or export separate PDFs. No uploads.',
    seoKeywords: 'image to pdf, jpg to pdf, png to pdf, convert images to pdf, photo to pdf converter',
  },
];

// Keys of the newly launched utility tools, used to feature them in a dedicated homepage promo.
export const NEW_UTILITY_TOOL_KEYS = ['notepad', 'jsonformatter', 'passwordgen', 'diffchecker', 'qrcode', 'base64', 'mdpreview', 'wordcounter', 'img2pdf'];

export const NAV_LINKS = TOOLS.map(({ key, label }) => ({ label, tool: key, href: '#tool' }));

export const FAQ_ITEMS = [
  {
    q: 'Are all the tools really free?',
      a: 'Yes. Every tool — shrinking, background removal, cropping, filters, moustachify, AI image generation, text to image, document conversion, video compression and audio extraction — is free to start, with fair-use limits on AI generation.',
  },
  {
    q: 'Do my files get uploaded to a server?',
    a: 'No. Every tool runs entirely in your browser. Your photos, documents and videos never leave your device.',
  },
  {
    q: 'How accurate is the PDF → Word conversion?',
    a: 'It extracts the text and turns each page into Word paragraphs. Plain, text-heavy PDFs convert beautifully. Complex layouts, scanned PDFs, tables and images may not survive the trip.',
  },
  {
    q: 'How accurate is the Word → PDF conversion?',
    a: 'Standard documents with text, headings and lists convert cleanly. Heavily styled documents with custom fonts and complex tables may render slightly differently.',
  },
  {
    q: 'How big a video can I compress?',
    a: 'Videos up to around 500 MB work reliably in most modern browsers. Bigger files can hit your browser memory limit. Compression and audio extraction are CPU-heavy operations.',
  },
  {
    q: 'Which file formats are supported?',
    a: 'Images: JPG, PNG, WEBP, BMP, GIF. Documents: PDF and DOCX. Video: MP4, MOV, WebM, MKV. Audio output: MP3.',
  },
  {
    q: 'Can I use these tools on my phone?',
    a: 'Yes. Everything works in modern mobile browsers — though background removal, video compression, moustachify and document conversion are noticeably faster on a desktop.',
  },
  {
    q: 'How does Moustachify work?',
    a: 'Moustachify uses face detection technology to identify faces in your image, then automatically applies a moustache with your chosen style. Choose from 6 fun styles and adjust the size to your liking.',
  },
  {
    q: 'How does AI image generation work here?',
    a: 'The AI Image Generator sends your prompt and settings to Hugging Face Inference API. Most images generate in 2-10 seconds. Free tier access follows fair-use and rate limits.',
  },
  {
    q: 'Are the Notepad, JSON Formatter and other new utility tools free too?',
    a: 'Yes — Notepad, JSON Formatter, Password Generator, Diff Checker, QR Code Generator, Base64 Encoder/Decoder, Markdown Previewer and Word Counter are all free, with no account or sign-up required.',
  },
  {
    q: 'Do the new utility tools also keep my data private?',
    a: "Yes. They run entirely in your browser — nothing is uploaded to a server. The Notepad autosaves to this browser's local storage only, so it stays on your device and isn't accessible from anywhere else.",
  },
  {
    q: 'Is the Password Generator actually secure?',
    a: "Yes. It uses your browser's built-in cryptographic random number generator (Web Crypto API), the same standard used for security-sensitive code — not a simple pseudo-random function. Passwords are generated locally and never transmitted anywhere.",
  },
  {
    q: 'Is it safe to paste sensitive text into the Markdown Previewer or Diff Checker?',
    a: 'Yes — both tools process everything locally in your browser and rendered output is sanitized to strip any embedded scripts, so nothing you paste is sent to a server or executed unsafely.',
  },
];

export const USE_CASES = [
  'Publishing photos on websites for faster page loading',
  'Creating product shots with transparent backgrounds',
  'Cropping headshots and thumbnails to perfect dimensions',
  'Adjusting brightness, contrast and other photo effects',
  'Adding fun moustaches to photos for social media',
  'Turning PDF notes back into editable Word documents',
  'Sharing Word reports as polished PDF attachments',
  'Compressing videos for email, messaging and social uploads',
  'Extracting audio from videos for podcasts and clips',
  'Generating AI artwork, concept designs and social graphics from text prompts',
  'Creating text graphics and quote images for social media',
];
