// Mock data for PixelShrink Studio (frontend-only)
import { Scissors, Eraser, Crop as CropIcon, FileText, FileType2, Video, Music, Sparkles, Smile, Type } from 'lucide-react';

export const TOOLS = [
  {
    key: 'shrink',
    label: 'Shrink Image',
    short: 'Shrink',
    icon: Scissors,
    headline: 'Image Shrinker — resize images online, free.',
    sub: 'Shrink JPG, PNG, WEBP and more without losing crispness. Perfect for socials, email and the web.',
    seoTitle: 'Free Image Resizer Online | Shrink Images Without Quality Loss',
    seoDesc: 'Resize and compress JPG, PNG, WEBP images online. Shrink for web, email and social media while maintaining quality.',
    seoKeywords: 'image resizer, shrink image, compress image, resize image online, image compressor',
  },
  {
    key: 'removebg',
    label: 'Remove Background',
    short: 'No-BG',
    icon: Eraser,
    headline: 'Remove Background — instant, AI-powered, free.',
    sub: 'Erase backgrounds in one click. Get crisp transparent PNGs ready for product shots, designs and social posts.',
    seoTitle: 'Remove Background from Image | Free AI-Powered Background Remover',
    seoDesc: 'Remove image backgrounds instantly with AI. Get transparent PNGs for product photos, designs and social media.',
    seoKeywords: 'remove background, background remover, transparent PNG, AI background removal',
  },
  {
    key: 'crop',
    label: 'Crop Image',
    short: 'Crop',
    icon: CropIcon,
    headline: 'Crop Image — pick the perfect frame, free.',
    sub: 'Drag to crop, lock to a preset aspect ratio, and download the result. All in your browser.',
    seoTitle: 'Free Online Image Cropper | Crop Photos to Perfect Size',
    seoDesc: 'Crop images online with preset aspect ratios. Perfect for thumbnails, profile pictures and social media.',
    seoKeywords: 'image cropper, crop photo, resize aspect ratio, thumbnail maker, crop image online',
  },
  {
    key: 'filters',
    label: 'Image Filters',
    short: 'Filters',
    icon: Sparkles,
    headline: 'Image Filters — adjust brightness, contrast & more, free.',
    sub: 'Apply professional photo filters instantly. Adjust brightness, contrast, and grayscale right in your browser.',
    seoTitle: 'Free Online Photo Filters & Editor | Adjust Brightness, Contrast & Grayscale',
    seoDesc: 'Apply professional photo filters instantly. Adjust brightness, contrast, and grayscale on your images.',
    seoKeywords: 'photo filters, image editor, brightness contrast adjustment, photo effects, online photo editor',
  },
  {
    key: 'moustachify',
    label: 'Moustachify',
    short: 'Stache',
    icon: Smile,
    headline: 'Moustachify — add a moustache to any face, free.',
    sub: 'Automatic face detection adds a perfect moustache to your photo. Choose from 6 fun styles.',
    seoTitle: 'Moustachify — Add Moustache to Photos | Free Face Detection Tool',
    seoDesc: 'Add fun moustaches to any face with AI face detection. Choose from 6 styles: handlebar, pencil, walrus, curly, chevron, dutch.',
    seoKeywords: 'moustachify, add moustache, face detection, fun photo editor, mustache filter, photo effects',
  },
  {
    key: 'pdf2word',
    label: 'PDF → Word',
    short: 'PDF→Word',
    icon: FileText,
    headline: 'PDF to Word — extract text from PDFs, free.',
    sub: 'Convert text-based PDFs into editable Word documents. Layout-light PDFs convert best.',
    seoTitle: 'Convert PDF to Word Online | Free PDF to Docx Converter',
    seoDesc: 'Convert text-based PDF files to editable Word documents. Extract text and maintain formatting.',
    seoKeywords: 'pdf to word, convert pdf to docx, pdf converter, extract text from pdf',
  },
  {
    key: 'word2pdf',
    label: 'Word → PDF',
    short: 'Word→PDF',
    icon: FileType2,
    headline: 'Word to PDF — turn docs into PDFs, free.',
    sub: 'Drop your .docx file and get back a clean, shareable PDF in seconds.',
    seoTitle: 'Convert Word to PDF Online | Free DOCX to PDF Converter',
    seoDesc: 'Convert Word documents (.docx) to PDF instantly. Create professional PDFs for sharing and printing.',
    seoKeywords: 'word to pdf, convert docx to pdf, pdf converter, docx to pdf converter',
  },
  {
    key: 'compressvideo',
    label: 'Compress Video',
    short: 'Video',
    icon: Video,
    headline: 'Video Compressor — shrink video files, free.',
    sub: 'Compress MP4, MOV and WebM files without losing too much quality. Runs entirely in your browser.',
    seoTitle: 'Compress Video Online | Free MP4, MOV & WebM Compressor',
    seoDesc: 'Reduce video file size without losing quality. Compress MP4, MOV, WebM for email and social media.',
    seoKeywords: 'video compressor, compress video, reduce video size, mp4 compressor, video compression',
  },
  {
    key: 'video2mp3',
    label: 'Video → MP3',
    short: 'V→MP3',
    icon: Music,
    headline: 'Video to MP3 — extract audio, free.',
    sub: 'Pull the audio out of any video file you own. Get a clean MP3 ready to share.',
    seoTitle: 'Convert Video to MP3 | Free Audio Extraction Tool',
    seoDesc: 'Extract audio from videos and download as MP3. Works with MP4, MOV, WebM files.',
    seoKeywords: 'video to mp3, extract audio, convert video to audio, mp3 converter, audio extractor',
  },
  {
    key: 'texttoimage',
    label: 'Text to Image',
    short: 'Txt→Img',
    icon: Type,
    headline: 'Text to Image — create stunning graphics from text, free.',
    sub: 'Turn any text into a beautiful image. Choose fonts, colors, effects and canvas sizes for social media.',
    seoTitle: 'Text to Image Creator | Free Online Generator',
    seoDesc: 'Create beautiful images from text. Customize fonts, colors, effects and download instantly.',
    seoKeywords: 'text to image, image generator, create images, text graphics, quote maker',
  },
];

export const NAV_LINKS = TOOLS.map(({ key, label }) => ({ label, tool: key, href: '#tool' }));

export const FAQ_ITEMS = [
  {
    q: 'Are all the tools really free?',
      a: 'Yes. Every tool — shrinking, background removal, cropping, filters, moustachify, text to image, document conversion, video compression and audio extraction — is completely free, with no sign-up required.',
  },
  {
    q: 'Do my files get uploaded to a server?',
    a: 'No. Every tool runs entirely in your browser. Your photos, documents and videos never leave your device.',
  },
  {
    q: 'How accurate is the PDF → Word conversion?',
    a: 'It extracts the text and turns each page into Word paragraphs. Plain, text-heavy PDFs convert beautifully. Complex layouts, scanned PDFs, tables and images may not survive the trip.',
  },
  {
    q: 'How accurate is the Word → PDF conversion?',
    a: 'Standard documents with text, headings and lists convert cleanly. Heavily styled documents with custom fonts and complex tables may render slightly differently.',
  },
  {
    q: 'How big a video can I compress?',
    a: 'Videos up to around 500 MB work reliably in most modern browsers. Bigger files can hit your browser memory limit. Compression and audio extraction are CPU-heavy operations.',
  },
  {
    q: 'Which file formats are supported?',
    a: 'Images: JPG, PNG, WEBP, BMP, GIF. Documents: PDF and DOCX. Video: MP4, MOV, WebM, MKV. Audio output: MP3.',
  },
  {
    q: 'Can I use these tools on my phone?',
    a: 'Yes. Everything works in modern mobile browsers — though background removal, video compression, moustachify and document conversion are noticeably faster on a desktop.',
  },
  {
    q: 'How does Moustachify work?',
    a: 'Moustachify uses face detection technology to identify faces in your image, then automatically applies a moustache with your chosen style. Choose from 6 fun styles and adjust the size to your liking.',
  },
];

export const USE_CASES = [
  'Publishing photos on websites for faster page loading',
  'Creating product shots with transparent backgrounds',
  'Cropping headshots and thumbnails to perfect dimensions',
  'Adjusting brightness, contrast and other photo effects',
  'Adding fun moustaches to photos for social media',
  'Turning PDF notes back into editable Word documents',
  'Sharing Word reports as polished PDF attachments',
  'Compressing videos for email, messaging and social uploads',
  'Extracting audio from videos for podcasts and clips',
  'Creating text graphics and quote images for social media',
];
